/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// 141. Linked List Cycle
// https://leetcode.com/problems/linked-list-cycle/

public class App {
    public static void main(String[] args) {
        ListNode head = new ListNode(3);
        head.next = head; // new ListNode(2);
        // head.next.next = new ListNode(0);
        // head.next.next.next = new ListNode(-4);
        // head.next.next.next.next = head.next;
        //head.next.next.next = head;
        //head.next.next.next = null;
        
        Solution solution = new Solution();
        Boolean result = (Boolean) solution.hasCycle(head);
        System.out.println(result.toString());
    }
}
