/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        ListNode nodeC = new ListNode(6);
        nodeC.next = new ListNode(7);
        
        ListNode headA = new ListNode(1);
        headA.next = new ListNode(2);
        headA.next.next = nodeC;

        ListNode headB = new ListNode(3);
        headB.next = new ListNode(4);
        headB.next.next = new ListNode(5);
        // headB.next.next.next = nodeC;

        Solution solution = new Solution();
        ListNode result = solution.getIntersectionNode(headA, headB);
        System.out.println(result);
    }
}
